ci: update actions/upload-artifact to v4
The release workflow failed because actions/upload-artifact@v1 doesn't work anymore.

https://github.com/Byron/dua-cli/actions/runs/11649383977/job/32436848048

```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```